### ISSUE TITLE
Good ML work for maplestory

### ISSUE THREAD

**Issue by kino0924** [charlescao460/MapleStory_TFRecord_Preparer#3]
Hi, I am also interested with working maplestory with ML
I would love to discuss with you about my progress and challenges with ML on maplestory
Discord : KINO#2595
Please please please reach me. I cannot find any ways to reach you

**Comment by charlescao460** [comment]
Hi, thanks for liking this project.
Actually, you can find my email from git history... That should be common knowledge.
I still prefer to have a discussion here at GitHub, since anyone else can see the conversion and share thoughts. 

But anyway, I've sent a request to you Discord.
